### ISSUE TITLE
live version not up-to-date

### ISSUE THREAD

**Issue by silberzwiebel** [r-transit/analyze-transit-data-with-r#1]
Hi there,

@mpadge pointed me to this promising new project `r-transit`. In the process of getting used to the packages here (and to working with transit data in the first place), I started to have a look at http://howto.r-transit.org/. I wanted to open a PR adding missing dependencies to the installation instructions just to learn that the [live documentation](http://howto.r-transit.org/) is not yet up-to-date: it still refers to `tidytransit` that has, via its R dependencies, system dependencies for `udunits2-devel, gdal-devel, proj-devel, proj-nad, proj-epsg` and `geos-devel`.

The github doc version points to `trread` which installs fine without dependency.
The next section, however, fails again: `trread` does not (yet?) have a `feedlist` variable.

I believe that this is a young project, so forgive me if I'm just to impatient :)

**Comment by tbuckl** [comment]
thanks @silberzwiebel i just made the live docs match the github docs. 

you raise a number of other specific issues:

https://github.com/r-transit/analyze-transit-data-with-r/issues/2

https://github.com/r-transit/analyze-transit-data-with-r/issues/3

**Comment by tbuckl** [comment]
@silberzwiebel i'm going to close this out since i think its resolved. feel free to reopen if you like. you should be able to edit this doc set now and then i can push it to the other bucket. the other issues will have to be resolved separately

**Comment by tbuckl** [comment]
@silberzwiebel also, yes, the CRAN version of `trread` does not have a feedlist. it will in the next CRAN release. 

for now, you can download one from here:

https://github.com/r-transit/trread/raw/master/data/feedlist.rda
